name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: magicroute-web/package-lock.json

      - name: Install dependencies
        run: |
          cd magicroute-web
          npm install

      - name: Build
        run: |
          cd magicroute-web
          npm run build
        env:
          VITE_API_URL: https://magicroute-john-api.loca.lt
          VITE_GOOGLE_MAPS_API_KEY: AIzaSyAmta1q0E63ZqjWC-T-OwydVBIzhFFvnSY

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: magicroute-web/dist
          branch: gh-pages
